### ISSUE TITLE
Fix Bootstrap import paths

### ISSUE THREAD

**Issue by tonifisler** [frontend/generator-toolbox#20]
Currently, all `@import` paths in `bootstrap.scss` are set to `../../node_modules/…`

This makes the gulp task `styles` crash without any error logged when the `assets/` folder is not at the root of the project (i.e. in a Drupal or WP theme). We need to dynamically generate the right path with the right number of `../` 😉

**Comment by Yago** [comment]
`/app/templates/assets/sass/bootstrap.scss` should be “templated”
