### ISSUE TITLE
Add Tasks for Singles files

### ISSUE THREAD

**Issue by WengerK** [frontend/generator-toolbox#22]
**Allow the generator to create separated (un-concatenated) files.**

It's useful for Drupal for example, using a core jQuery, we need a separated file for the styleguide.
Or for CKeditor of Drupal, avoid using same all css for CKeditor.
- Single vendors
- Single Styles
- Single Scripts

**Comment by Yago** [comment]
Check if we can loop over a [{file, dest}] config array to create a single and dynamic `single-file` task

C.f. [stackoverflow](http://stackoverflow.com/a/26786529/2995266)

**Comment by Yago** [comment]
will continue in #46
