### ISSUE TITLE
Paths issues on gh-pages

### ISSUE THREAD

**Issue by tonifisler** [frontend/generator-toolbox#24]
When on `gh-pages`, the styleguide is in a sub-folder. All paths written as `/build/css/...` are then completely wrong. I suggest building the styleguide in a sufolder from the start in `styleguide/repo-name/`. We need to update the generating tasks accordingly. 😉 

And remember that Github is case-sensitive.

**Comment by tonifisler** [comment]
Cf. what I did for https://github.com/antistatique/fristyle

**Comment by Yago** [comment]
I nice lead is using a `{{data.base}}` dynamic value based on CLI parameter :wink:

Cf. https://github.com/antistatique/evam360-styleguide/commit/1e1750e8cc2454d8758813a7303489c9345f7372

**Comment by Yago** [comment]
will continue on #47
