### ISSUE TITLE
Linter and general config file

### ISSUE THREAD

**Issue by Yago** [frontend/generator-toolbox#27]
- Externalize ?
- [Stylelint config standard](https://github.com/stylelint/stylelint-config-standard) ?
- Eslint [Airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) ?
- Fail git push hook :smiling_imp:
- Config Dev/Prod ± permissive

**Comment by Yago** [comment]
We can also add a `.stylelintignore`

**Comment by tonifisler** [comment]
@Yago already an issue for this: #25 😉

**Comment by Yago** [comment]
Nice !

**Comment by Yago** [comment]
- [ ] Add 2 level of linting (default name for dev, and custom for prod)
- [x] Install and extend Airbnb eslint config
- [x] Instal, extend and add order for stylelint config
- [ ] Hook pre-push fail when linter has errors
