### ISSUE TITLE
Optimize DevDependencies

### ISSUE THREAD

**Issue by Yago** [frontend/generator-toolbox#29]
Using [slow-deps](https://github.com/nolanlawson/slow-deps)

**Comment by tonifisler** [comment]
Slow ones: 

| Dependency | Time | Size | # Deps |
| :-- | --: | --: | --: |
| gulp-imagemin | 1m 11.5s | 9.6 MB | 298 |
| gulp-iconfont | 1m 9s | 25 MB | 231 |
| imagemin-pngquant | 51.4s | 4.9 MB | 266 |
| browser-sync | 51.1s | 32 MB | 250 |
| webpack-stream | 46.1s | 15 MB | 209 |
| webpack | 43.7s | 14 MB | 191 |
| gulp-sass | 43.4s | 14 MB | 216 |
| gulp | 40.3s | 9.1 MB | 198 |
| gulp-eslint | 35.6s | 12 MB | 197 |
| gulp-metalsmith | 34.8s | 5.5 MB | 172 |
