### ISSUE TITLE
Swig is deprecated and not maintained anymore

### ISSUE THREAD

**Issue by tonifisler** [frontend/generator-toolbox#36]
Source: https://github.com/paularmstrong/swig/commit/70a1c8899266893ff22354c2426329e306c2f322

A fork exists: https://github.com/node-swig/swig-templates

We should maybe find another template engine! (compatible with consolidate.js)

**Comment by Yago** [comment]
A good solution could be to use [Twig.js](https://github.com/twigjs/twig.js) which is pretty nicely supported and based on the [Metalsmith-twig](https://github.com/PKuebler/metalsmith-twig), we can make a fork and fix the [issue](https://github.com/twigjs/twig.js/issues/262) we have.

**Comment by Yago** [comment]
So we are in deep 💩  Twig.js is really hard to implement to our metalsmith workflow. So for know, we will still use the unmaintained Swig with the hope of a [swig-template](https://github.com/node-swig/swig-templates) maintain soon...
