### ISSUE TITLE
Add recurrent sass snippet

### ISSUE THREAD

**Issue by Yago** [frontend/generator-toolbox#38]
Add (by default or prompted ?) SCSS snippets like : 
- Spacers
- Responsive typography
- ...

**Comment by tonifisler** [comment]
**Spacers** are not really needed anymore thanks to Bootstrap 4: [**Spacing** doc](http://v4-alpha.getbootstrap.com/components/utilities/#spacing)

**Responsive typography** is not really needed anymore thanks to Bootstrap 4 using `rem` throughout everything. [**Responsive typography** doc](http://v4-alpha.getbootstrap.com/content/typography/#responsive-typography)
