### ISSUE TITLE
Don't regenerate every images every time

### ISSUE THREAD

**Issue by WengerK** [frontend/generator-toolbox#49]
It could be nice to avoid image generating every time :D

**Comment by tonifisler** [comment]
> We usually already have optmized images.
> 
> See report of slow-deps: https://github.com/frontend/generator-toolbox/issues/29#issuecomment-248236237

**Comment by tonifisler** [comment]
Done in 77a4460666a0cd9e4835025b4f646825395fc622

**Comment by WengerK** [comment]
![Image of Yaktocat](https://media.giphy.com/media/GODSCQebffJzW/giphy.gif)
