### ISSUE TITLE
[package.json] Split what is `devDependencies` from what is not

### ISSUE THREAD

**Issue by gido** [frontend/generator-toolbox#9]
## Why ?

Because I don't want to compile phantomjs or browser-sync for preparing production build.
## How ?

```
npm install --production
```

should be just enough to run `gulp build`

**Comment by Yago** [comment]
It's on my todo since a while, but it's planned :wink:

**Comment by Yago** [comment]
Done. Now we will optimize the truly needed dependencies to speed up installation. C.f. #29
