### ISSUE TITLE
Allow components to be in hierarchy  

### ISSUE THREAD

**Issue by dmrty** [frontend/generator-toolbox#96]
Especially, I end up with `blocs/bloc-author` and `blocs/bloc-links` as variations. But semantically it should not be variations but components.

**Comment by Yago** [comment]
No big teasing, but soon, you will have more control over the classic atoms/molecules/organisms/page directory structure 😉

**Comment by Yago** [comment]
Hi @dmrty, I just publish a big batch of new features for Toolbox, including a more flexible component organisation.

I invite you to check the [post about the release](https://github.com/frontend/toolbox/wiki/June-2018-updates) and see if it fits to your needs 😉
