### ISSUE TITLE
Include layouts as a new type of components.

### ISSUE THREAD

**Issue by dmrty** [frontend/generator-toolbox#97]
I end up wrapping things around quite often. 

Especially, I end up with 
* `pages/layouts-main`
* `pages/layouts-homepage` 
*`pages/layouts-fullwidth` 

That would be nice to have `layouts/main`, `layouts/homepage` `layouts/fullwidth` instead.

Also for blocs, `layouts/bloc`

**Comment by Yago** [comment]
Same teasing here, but you will be soon hable to create your own directory structure to fits to your project's needs.

**Comment by dmrty** [comment]
Cool.

If you need help 🤚

**Comment by Yago** [comment]
Hi @dmrty, I just publish a big batch of new features for Toolbox, including a more flexible component organisation.

I invite you to check the [post about the release](https://github.com/frontend/toolbox/wiki/June-2018-updates) and see if it fits to your needs 😉

**Comment by dmrty** [comment]
Works for me.
