### ISSUE TITLE
Generator dafuk since v2.1.0

### ISSUE THREAD

**Issue by dmrty** [frontend/generator-toolbox#98]
It seems the published package does not contain the ../check-update module (once removed from the main.js, the generator works). It is indeed not present in the npm package.

🤷‍♂️

**Comment by dmrty** [comment]
It seems it is just a package.json files defect. Do you want a PR ?

**Comment by Yago** [comment]
I'll check it today. Thanks for the repport !

**Comment by Yago** [comment]
Ok, it comes from our package.json who doesn't include the new stuff. It has been fixed in the new `2.1.2`.

Thanks again for spoting it so quickly 😄👍
