### ISSUE TITLE
Slug is still mandatory

### ISSUE THREAD

**Issue by dmrty** [frontend/generator-toolbox#99]
hej 
Not sure why remove it off variant and generate, as it is used in the code still :-/
https://github.com/frontend/generator-toolbox/blob/7f5afae9be45a96da423bc2cecc1bfef172b38e7/generators/generate/index.js#L68

Generators broken right now , with new version v 2.1.2

**Comment by Yago** [comment]
Ok, I will take a look asap. Thanks for repporting !

**Comment by Yago** [comment]
Release [2.1.3](https://github.com/frontend/generator-toolbox/releases/tag/2.1.3) will fix your issue 😄

**Comment by dmrty** [comment]
hmm. Corrected only for `generate`, but still missing for `variant`, from what i can see :-/.

**Comment by Yago** [comment]
🤔 Normally, the `variant` generator doesn't need `slug`...

**Comment by dmrty** [comment]
🤦‍♀️ Well. that's a case of "should have tested first".

My appologies.

**Comment by Yago** [comment]
No problem 😉
